### ISSUE TITLE
feat(dm-cli): be able to handle non-contained attributes on disk

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-cli#104]
```
{
  "employees": [
    {
     "type": "dmss://system/SIMOS/Reference",
    "address": "./entity1.json",
    "referenceType": "storage"
    }
  ]
}

```

The employees are pointing to a Employee blueprint.

**Comment by KristianKjerstad** [comment]
does not contain enough info to start on this task.


- in what way should non contained attributes be handled on disk?
- what is missing from the current implementation to make it work?

**Comment by eoaksnes** [comment]
Options:
- [ ] Place all storage un-contained files directly under the data source folder
- [ ] Use a special symbol like _ for files, to say that they should not be included in the package content
- [ ] Have it resolved on disc
- [ ] Use _meta_ information inside file to say that it is storage uncontained

**Comment by eoaksnes** [comment]
Tip: Use alias to point on disk

**Comment by eoaksnes** [comment]
In the data source .json file, add a meta information field, that says what folders include files that should be uploaded directly to the data source without being added inside a package. 


Can be something like this:

```
{
  "file-folders" : [ nameOfFolder ]
}
```
