### ISSUE TITLE
fix: check if validation runs only on root folders, not on single files inside a datasource

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-cli#114]

**Comment by eoaksnes** [comment]
@KristianKjerstad do you have some more context about the issue? Is the validation not complete, does it only validate root package folders and not children of the root package?

**Comment by KristianKjerstad** [comment]
when @roar-larsen was running dm-cli reset command, it looked like the script tried to validate a root package called "DemoDataSource/.DS_STORE"

which indicates that the validation part of dm reset interprets single files as root packages. Correct behavior is to only interpret folders as root package
