### ISSUE TITLE
Importing single entities

### ISSUE THREAD

**Issue by soofstad** [equinor/dm-cli#30]
- [x] Determine DMSS endpoint to use:
  - [ ] `dmss_api.document_add_simple` (add raw, i.e. `data_source_id`)?
  - [ ] or `dmss_api.document_add` (add by parent id, i.e. `absolute_ref`)?
  - [x] or `dmss_api.document_add_to_path` (add by path, i.e. `path_reference`)?
- [x] Implement a function, `import_single_entity` in the `bin/dm` file:
  - `import_single_entity(path_to_entity: Path, path_reference: str)`
- [x] Create file `import_entity.py`
  - [ ] Implement functionality for:
    - [x] Reading the entity from disk (given path)
    - [x] Replace relative references
    - [x] Upload blobs
    - [x] Upload document to `path_reference` using the given endpoint
- [ ] Document new CLI function in `README`

# User story

As a user, I need to import single entities, so that I can work against external systems

**Comment by KristianKjerstad** [comment]
add option to work with single entities - right now the meta information is defined in a package. We must change this and let meta data be in a blueprint (so it exists on every entity).

**Comment by KristianKjerstad** [comment]
We should be careful when importing a lot of entities.

if we import 20 000 entities, we must do something smart to somehow let each entity inherit meta from the package or something
