### ISSUE TITLE
fix: MIGHT BE FIXED - when resetting with dm-cli, primitive types are mapped resolved incorrectly (see screenshot)

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-cli#50]
the primitive type string should not be converted to "'dmss: //DemoApplicationDataSource/models/string"

![Image](https://user-images.githubusercontent.com/69512295/208399887-84e90d3a-b3da-4152-a4b1-555a1e16bf74.png)

**Comment by netr0m** [comment]
This has been resolved with the latest version of `dm-cli` (ref https://github.com/equinor/dm-cli/pull/49)
