### ISSUE TITLE
feat: import plugin blueprints to system://plugins

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-cli#64]
some plugins in the dm-core-packages repo requires their own blueprints (for example, the form plugin has the FormInput.json blueprint located inside dm-core-plugins/blueprints folder in the repo.) These blueprints are included in the npm package. 

instead of letting the user manually copy the blueprint from node_modules/@development-framework/dm-core-plugins/blueprints/form, we want a command in dm-cli that copies all plugin related blueprints to dmss into a root package called plugins under the system datasource.

**Comment by soofstad** [comment]
Final command should look like:
```
dm import-plugin-blueprints ./node_modules/package
```

**Comment by l3abak** [comment]
It works after using the new format for dm-cli
