### ISSUE TITLE
refactor: separate cli commands into use cases

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-cli#75]
the whole codebase would be more maintainable if we extract the code from each command into a separate "standard python function" / use case in separate files.

So that the functions with the click decorators only extract the arguments, and then pass them to a "backend function".

Then we would not need to do this "context.invoke()" thing either.
Would then also need to pass the "dmss_api" object I suppose.

**Comment by KristianKjerstad** [comment]
example:

```python
@pkg_cli.command("delete-all", help="Delete all packages found in the directory given by <path> from the given data source.")
@click.argument("data_source", required=True)
@click.argument("path", required=True)
@click.pass_context
def delete_packages(context, data_source: str, path: str):
    """
    Delete all packages found in the directory given by <path> from the given data source
    """
    data_source_data_dir = Path(path)
    delete_packages_from_directory_use_case(data_source, data_source_data_dir)


```

**Comment by soofstad** [comment]
Done
